// <auto-generated />
namespace Polagora.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSnapshots : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSnapshots));
        
        string IMigrationMetadata.Id
        {
            get { return "201608081723415_AddSnapshots"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
